django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('onlyplans.urls')),
    path('accounts/',include('accounts.urls')),
    path('events/', include('events.urls')),
    path('user/', include('friends.urls')),
]

django_project/events/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.register),
    path('<id>/', views.display),
]

django_project/events/forms.py
from django.forms import ModelForm
from onlyplans.models import OnlyPlan
from django.core.exceptions import ValidationError
from django import forms

class storeEventForm(ModelForm):
    title = forms.CharField(max_length=140, label="Titill")
    location_latitude = forms.FloatField(max_value=90, min_value=-90, label="")
    location_longitude = forms.FloatField(max_value=180, min_value=-180, label="")
    reach = forms.IntegerField(max_value=30, min_value=0, label="")
    when = forms.DateTimeField(label="Tímasetning", input_formats=['%Y/%m/%d %H:%M'])
    duration = forms.ChoiceField(choices=(('1', 'eitt augnablik'), ('10', 'smá stund'), ('30', 'hálftíma'), ('60', 'klukkutíma'), ('240', 'nokkra klukkutíma'), ('360', 'hálfan dag'), ('1440', 'sólarhring'), ('2880', 'tvo daga'), ('10000', 'viku')), label="Lengd")
    friendsonly = forms.BooleanField(label="Bara fyrir vini", required=False)

    def clean_title(self):
        data = self.cleaned_data['title']
        return data

    def clean_location_latitude(self):
        data = self.cleaned_data['location_latitude']
        return data
        
    def clean_location_longitude(self):
        data = self.cleaned_data['location_longitude']
        return data

    def clean_when(self):
        data = self.cleaned_data['when']
        return data

    def clean_duration(self):
        data = self.cleaned_data['duration']
        return data

    def clean_reach(self):
        data = self.cleaned_data['reach']
        return data

    def clean_friendsonly(self):
        data = self.cleaned_data['friendsonly']
        return data

    class Meta:
        model = OnlyPlan
        fields = ['title', 'location_latitude', 'location_longitude', 'when', 'duration', 'reach', 'friendsonly']

django_project/events/views.py
from django.shortcuts import redirect, render, HttpResponseRedirect
from onlyplans.models import OnlyPlan
from events.forms import storeEventForm
from friendship.models import Friend
from django.contrib.auth.models import User

# Create your views here.
def register(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = storeEventForm(request.POST)

            if form.is_valid():
                event = form.save(commit=False)
                event.owner = request.user
                event.save()
                return redirect('/')
        else:
            form = storeEventForm()
        return render(request, 'events.html', {'form': form})
    else:
        return HttpResponseRedirect('/accounts/')

def display(request, id):
    event_qs = OnlyPlan.objects.filter(id=id)
    
    if event_qs:
        event = event_qs[0]
        event_owner_qs = User.objects.filter(username=event.owner)

        can_see_event = False

        if event_owner_qs:
            event_owner = event_owner_qs[0]
            if not event.friendsonly:
                can_see_event = True
            elif Friend.objects.are_friends(request.user, event_owner):
                can_see_event = True
            elif event_owner == request.user:
                can_see_event = True
            
            if can_see_event:
                if event_owner.get_full_name() != "":
                    person_name = event_owner.get_full_name()
                else:
                    person_name = event_owner.username

                context = { 'event': event, 'owner': person_name }
                return render(request, 'showevent.html', context)

    return HttpResponseRedirect('/')

django_project/events/templates/events.html
{% extends 'base.html' %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<!-- XDSoft DateTimePicker -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>
<link href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" rel="stylesheet"/>

<h2>Vista nýjan atburð</h2>
<form method="POST">
     {% csrf_token %}
    {{form.as_p}}
    <h3>Veldu staðsetningu</h3>
    <span class="functiontext"><a href="#" onclick="huntDown();">finna núverandi staðsetningu</a></span>
    <br>
    <div style="width: 400px; height: 400px;" id="osm-map"></div>
    <br><br>
    <button>Skrá</button>
</form>

<script>
    el_lat = document.getElementById('id_location_latitude');
    el_lon = document.getElementById('id_location_longitude');
    el_reach = document.getElementById('id_reach');

    el_lat.style.display = 'none';
    el_lon.style.display = 'none';
    el_reach.style.display = 'none';
    
    var element = document.getElementById('osm-map');
    var map = L.map(element);
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OSM</a>'
    }).addTo(map);
    map.setView(L.latLng('64.15', '-21.85'), 10);
    tracer();

    function centerMap(position) {
        target = L.latLng(position.coords.latitude, position.coords.longitude);
        map.setView(target, 18);
    }

    function huntDown() {
        navigator.geolocation.getCurrentPosition(centerMap);
    }

    function tracer() {
        loc = map.getCenter();
        el_reach.value = map.getZoom();
        el_lat.value = loc.lat;
        el_lon.value = loc.lng;

        setTimeout("tracer();",200)
    }

    $(function () {
      $("#id_when").datetimepicker({
        format: 'Y/m/d H:i',
      });
    });
  </script>
{% endblock %} 

django_project/events/templates/showevent.html
{% extends 'base.html' %}

{% block content %} 
<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>
<link href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" rel="stylesheet"/>

<span class="authorbox"><a href="/user/{{ event.owner }}">{{ owner }}</a> kynnir:</span>
<h2>{{ event.title }}</h2>
<p class="datetag indent">{{ event.when|date:'d. m. k\l\ukk\a\n H:i' }}</p><span class="hidden">{{ event.when|date:'Y-m-d\TH:i:s\Z' }}</span>
<br>
<div style="width: 400px; height: 400px;" id="osm-map"></div>
<p><a href="/">Til baka</a></p>
<script>
    var element = document.getElementById('osm-map');
    var map = L.map(element);
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OSM</a>'
    }).addTo(map);
    map.setView(L.latLng('{{ event.location_latitude }}', '{{ event.location_longitude }}'), {{ event.reach }});
</script>

{% endblock %}